# Generated by Django 3.0.6 on 2020-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200707_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_admin', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_user', models.TextField()),
                ('body_admin', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
